//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.09 at 11:44:06 AM IST 
//


package com.mobikwik.max.bupa.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mobikwik.max.bupa.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SecuredWebServiceHeader_QNAME = new QName("http://tempuri.org/", "SecuredWebServiceHeader");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mobikwik.max.bupa.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUWDecision }
     * 
     */
    public GetUWDecision createGetUWDecision() {
        return new GetUWDecision();
    }

    /**
     * Create an instance of {@link GetUWDecisionResponse }
     * 
     */
    public GetUWDecisionResponse createGetUWDecisionResponse() {
        return new GetUWDecisionResponse();
    }

    /**
     * Create an instance of {@link LibraWebsiteCollectionDetails }
     * 
     */
    public LibraWebsiteCollectionDetails createLibraWebsiteCollectionDetails() {
        return new LibraWebsiteCollectionDetails();
    }

    /**
     * Create an instance of {@link LibraWebsiteCollectionDetailsResponse }
     * 
     */
    public LibraWebsiteCollectionDetailsResponse createLibraWebsiteCollectionDetailsResponse() {
        return new LibraWebsiteCollectionDetailsResponse();
    }

    /**
     * Create an instance of {@link SecuredWebServiceHeader }
     * 
     */
    public SecuredWebServiceHeader createSecuredWebServiceHeader() {
        return new SecuredWebServiceHeader();
    }

    /**
     * Create an instance of {@link InsertOnlineTransactionAgentsDetails }
     * 
     */
    public InsertOnlineTransactionAgentsDetails createInsertOnlineTransactionAgentsDetails() {
        return new InsertOnlineTransactionAgentsDetails();
    }

    /**
     * Create an instance of {@link InsertOnlineTransactionAgentsDetailsResponse }
     * 
     */
    public InsertOnlineTransactionAgentsDetailsResponse createInsertOnlineTransactionAgentsDetailsResponse() {
        return new InsertOnlineTransactionAgentsDetailsResponse();
    }

    /**
     * Create an instance of {@link AuthenticateUser }
     * 
     */
    public AuthenticateUser createAuthenticateUser() {
        return new AuthenticateUser();
    }

    /**
     * Create an instance of {@link AuthenticateUserResponse }
     * 
     */
    public AuthenticateUserResponse createAuthenticateUserResponse() {
        return new AuthenticateUserResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecuredWebServiceHeader }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SecuredWebServiceHeader }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SecuredWebServiceHeader")
    public JAXBElement<SecuredWebServiceHeader> createSecuredWebServiceHeader(SecuredWebServiceHeader value) {
        return new JAXBElement<SecuredWebServiceHeader>(_SecuredWebServiceHeader_QNAME, SecuredWebServiceHeader.class, null, value);
    }

}
